--Creacion de secuencias--
--Secuencia para clientes--
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE

--Secuencia para productos--
CREATE SEQUENCE SEQ_PRODUCTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE

--Secuencia para pedidos--
CREATE SEQUENCE SEQ_PEDIDOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


--Tabla para los pedidos--
CREATE TABLE CLIENTES (
    ID NUMBER DEFAULT SEQ_CLIENTES.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    TELEFONO VARCHAR2(10) NOT NULL,
    DIRECCION VARCHAR2(100),
    CONSTRAINT UK_CLIENTES_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_CLIENTES_TELEFONO UNIQUE (TELEFONO)
);

